### PR TITLE
Solution updated to VS2017, add support for VS2017.

### PR DESCRIPTION
**Pull request by DomasM**

### CODE REVIEW

**Comment by davemckeown** [comment]
Thank you @DomasM !

**Comment by DomasM** [comment]
It would be nice to update in VS Marketplace too. In case you no longer use VS, or don't have VS 2017 here is zipped build folder. [https://dl.dropboxusercontent.com/u/30912947/Misc/TidyTabs.zip](url)

**Comment by davemckeown** [comment]
@DomasM I am trying to build this in VS 2017, and working on VS 2019 support. Currently the project fails to load in VS2017 with the Visual Studio SDK installed.

I haven't used VS in last 4 years but recently acquired a MSDN subscription, so I am working on an update. Are you able to assist? I would like to validate that the project still builds and works in VS2012 through VS2017 before adding VS2019 support

**Comment by DomasM** [comment]
@davemckeown I have checked status of the project.
Here are my findings: 
1. project should be migrated  from packages.config to PackageReference (I have done so very easily)
https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
2. Visual Studio of required version if targeting < 2015 should be installed (i.e. https://github.com/madskristensen/ShortcutExporter/issues/14 , last comment)

I haven't used anything earlier than VS2105 in ages, and really don't want to even install it on my dev machine. It seems that updating project to support VS2019 should be [piece of cake](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) if we drop < VS2015 support. So that's my suggestion. Leave old version for the ones stuck with ancient software somewhere, but move on.

**Pull request merged**
